name: "Auto test PR"
on:
  issue_comment:
    types: [created]
jobs:
  autoTestPR:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, 'auto exclude test') && github.event_name != 'pull_request'
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: check python version
        run: |
          python -V
      - name: checkout current repo
        uses: actions/checkout@v2
        with:
          path: 'tests'
      - name: checkout TKG repo
        uses: actions/checkout@v2
        with:
          repository: 'renfeiw/TKG.git'
          ref: 'master'
          path: 'TKG'
      - name: run script
        run: |
          python TKG/scripts/testBot/disable.py -m "${{ github.event.comment.body }}" -i "${{ github.event.comment.html_url }}" -d "$GITHUB_WORKSPACE/tests"
      - name: test cannot be found
        if: failure()
        run: |
          curl -u github-actions:${{ secrets.GITHUB_TOKEN }} -d '{ "body":  "Cannot find the specified test to exclude. Action run: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}" }' -X POST ${{ github.event.issue.comments_url }}
      - name: Create Pull Request if change made
        uses: peter-evans/create-pull-request@v3
        with:
          path: 'tests'
          title: '${{ github.event.comment.body }}'
          body: |
            related: ${{ github.event.comment.html_url }}
            triggered by @${{ github.event.comment.user.login }}
          commit-message: |
            AUTO: ${{ github.event.comment.body }}
            - related: ${{ github.event.comment.html_url }}
          branch: 'autoTestPR'
          branch-suffix: 'random'
          signoff: 'true'