name: "Remove autoTestPR branch"
on:
  pull_request:
    types: [closed]
jobs:
  rmAutoTestPRBranch:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'auto exclude test') && startsWith(github.event.pull_request.head.ref, 'autoTestPR') && (github.event.pull_request.user.login == 'github-actions[bot]')
    steps:
      - name: add test exclude label
        env:
          issue: ${{ github.event.pull_request.issue.title }}
        run: |
          echo "$issue"
      - name: remove auto test PR branch when the PR is closed
        run: |
          curl -u github-actions:${{ secrets.GITHUB_TOKEN }} -X DELETE ${{ github.event.pull_request.head.repo.url }}/git/refs/heads/${{ github.event.pull_request.head.ref }}